import { Source_Sans_3 } from 'next/font/google';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import './globals.scss';

const pageFont = Source_Sans_3({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={pageFont.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
